version: "3"

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: calendar
      POSTGRES_DB: calendar

  mq:
    image: rabbitmq:3.8.17-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
